### ISSUE TITLE
Problems while unmounting /proc

### ISSUE THREAD

**Issue by daald** [docker-32bit/ubuntu#11]
While building locally (wily on a trusty host), I had the following error:

    + rm /var/chroot/wily/etc/resolv.conf
    + umount /var/chroot/wily/proc
    umount: /var/chroot/wily/proc: device is busy.
            (In some cases useful info about processes that use
             the device is found by lsof(8) or fuser(1))

I tried to unmount manually but didn't find a way to do it.

**Comment by dashohoxha** [comment]
The manual way to unmount it should be: `umount /var/chroot/wily/proc`

Maybe it was a temporary problem, did you try it again? Maybe you can try to add a `sleep 2` before the `umount` command.

**Comment by daald** [comment]
No, this didn't solve it. I called the same command 2 minutes later using `sudo umount /var/chroot/wily/proc`. And because of the static directory name (`/var/chroot/`) another try was blocked until next system reboot (`sudo rm -rf /var/chroot` also failed)

**Comment by dashohoxha** [comment]
I didn't try wily. Hopefully you will fix the problem and will report the solution.

**Comment by daald** [comment]
sudo lsof /var/chroot/wily/
    # there was a syslogd and an rsyslogd process
    sudo kill 31602 32336

The problem is that `apt-get -y install ubuntu-minimal` installs a full stack of software including daemons which it starts. These cannot be discovered (and killed) easily without a separate cgroup or similar. I recommend running such commands in a Dockerfile, similar to how Ubuntu does it: https://github.com/tianon/docker-brew-ubuntu-core/blob/50b3bf21537afb96d95ccb25996c7bceb16c38d8/trusty/Dockerfile , but this will force you to rewrite the whole script (or adopt the one from https://github.com/tianon/docker-brew-ubuntu-core/tree/dist)

**Comment by dashohoxha** [comment]
No. It is possible to find out the processes that are running inside a chroot and to kill them all. I have done this previously.

**Comment by dashohoxha** [comment]
Let me know if this patch does not fix the problem, because I cannot test it.

**Comment by daald** [comment]
That's very dangerous.

1) I have some lxc containers, processes there might also be killed. And the script runs as root and thus have many privilieges.

2) I would do something like this instead:

    (
      cd /proc &&
      for p in */root; do
        readlink $p | grep -q '^/var/chroot' || continue
        pid="${p%/*}"
        [ "$pid" != 'self' ] || continue
        kill $pid
      done
    )

I made my own solution now. It also solves the linux32 problem. https://github.com/daald/docker-brew-ubuntu-core-32bit
