### ISSUE TITLE
desired ubuntu version as argument

### ISSUE THREAD

**Issue by sanderjo** [docker-32bit/ubuntu#25]
I wanted a Bionic (18.04) i386 image, so I changed the code:
```
if [ -z "$1" ]
  then
    suite=xenial
  else
    suite="$1"
fi

```
(so: default ubuntu version is still Xenial)
and that works:

```
sudo ./build-image.sh bionic
sudo docker run --rm -it  32bit/ubuntu:bionic  bash

root@97483d6cd4c3:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

```
 
If you want, I can send a PR.

**Comment by dashohoxha** [comment]
Are you saying that you have tested this script for `bionic` and it works?

**Comment by dashohoxha** [comment]
Can you test again the modified version?
If it does not work, reopen this issue and then send a PR that closes it.

**Comment by sanderjo** [comment]
Works! Nice!
