### ISSUE TITLE
issue hit when install docker on Ubuntu-32 i686

### ISSUE THREAD

**Issue by ywxkman** [docker-32bit/ubuntu#26]
1. firstly, I run build-image.sh with your orignal image, looks like ok, but cannot execute docker cmd.
2.sencodly, I change the arch value to cater my linux system, but run .sh, but meet below error, don't know why. could you kindly help? thanks!
log information:
+ arch=i686
+ suite=bionic
+ chroot_dir=/var/chroot/bionic
+ apt_mirror=http://archive.ubuntu.com/ubuntu
+ docker_image=32bit/ubuntu:bionic
+ packages='debootstrap schroot apparmor'
+ which docker
/usr/bin/docker
+ apt-get install -y debootstrap schroot apparmor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
schroot is already the newest version (1.6.10-1ubuntu3).
apparmor is already the newest version (2.10.95-0ubuntu2.10).
debootstrap is already the newest version (1.0.78+nmu1ubuntu1.6).
0 upgraded, 0 newly installed, 0 to remove and 214 not upgraded.
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ debootstrap --variant=minbase --arch=i686 bionic /var/chroot/bionic http://archive.ubuntu.com/ubuntu
I: Retrieving InRelease 
I: Checking Release signature
I: Valid Release signature (key id 790BC7277767219C42C86F933B4FE6ACC0B21F32)
E: Invalid Release file, no entry for main/binary-i686/Packages

**Comment by dashohoxha** [comment]
There is no `arch=i686`: http://archive.ubuntu.com/ubuntu/dists/bionic/main/
