### ISSUE TITLE
docker image name without ':'

### ISSUE THREAD

**Issue by eeesebio** [docker-32bit/ubuntu#4]
I had to change the line
docker_image="32bit/ubuntu:${1:-14.04}"
to 
docker_image="32bit/ubuntu${1:-14.04}"
in the script so that the last command work (cat ubuntu.tgz | docker import - $docker_image). I had a problem with creating (or goin into) a folder whose name contains ':'.

**Comment by dashohoxha** [comment]
I just tested these in terminal (ubuntu+bash): `mkdir ubuntu:test` and `rmdir ubuntu:test` and it worked without problems. Maybe you are using a different shell/terminal.
