### ISSUE TITLE
repository 'dotcloud/docker' does not exist

### ISSUE THREAD

**Issue by mmsayyam** [docker-32bit/ubuntu#5]
Hi
After running this line "git clone dotcloud/docker $GOPATH/src/github.com/dotcloud/docker" for installing docker on 32bit ubuntu, i am getting this error "fatal: repository 'dotcloud/docker' does not exist". Any help would highly be appreciated.

**Comment by dashohoxha** [comment]
I have no idea what you are talking about. Most probably you are in the wrong project.
