### ISSUE TITLE
Where is the Dockerfile?

### ISSUE THREAD

**Issue by thorsummoner** [docker-32bit/ubuntu#6]

**Comment by dashohoxha** [comment]
There is no Dockerfile. The command `docker build` is only one of the ways for building a Docker image. But you can also build an image for LFS (http://www.linuxfromscratch.org/) and you don't need a Dockerfile for it.

**Comment by thorsummoner** [comment]
I found that there is an already generated image here: https://registry.hub.docker.com/u/32bit/ubuntu/

Which is what I really wanted.
