### ISSUE TITLE
Guide How To Install Docker on 32bit

### ISSUE THREAD

**Issue by ghprod** [docker-32bit/ubuntu#7]
Hi, 

any guide how to install docker itself on 32bit machine?

Thanks

**Comment by dashohoxha** [comment]
In ubuntu I have tried `aptitude install docker.io` and it has worked.

**Comment by ghprod** [comment]
wow you right ... i still remember that last month i cant install docker.io on my 32 bit machine, but now i can.. nice ...:+1:

![image](https://cloud.githubusercontent.com/assets/1922652/8741900/bd318b34-2c89-11e5-86ca-841a7ceeb74d.png)

so the next step just download image you've build on repo right?


Thanks

**Comment by dashohoxha** [comment]
Next step is either `docker pull 32bit/ubuntu` or
```
git clone https://github.com/docker-32bit/ubuntu
ubuntu/build-image.sh
```

**Comment by ghprod** [comment]
:+1:  Thanks a lot for your kindness..

Case closed
